/*
 * jQuery jPList Plugin
 * Copyright 2012 Miriam Zusin. All rights reserved.
 * To use this file you must to buy a licence at http://codecanyon.net/user/no81no/portfolio
 */
(function(g){var a={view_data:[]};a.update_sorting=function(c,f,b){a.paging.cpage=0;a.sort.sort_name=c;a.sort.order=f;a.sort.type=b;a.update_view()};a.update_paging=function(c){a.paging.items_on_page="all"==c?a.paging.all_items_num:c;a.paging.cpage=0;a.update_view()};a.print=function(c){for(var f="",b,e=a.sort.sort_name,d=a.paging.items_on_page,h=a.paging.cpage,k=a.sort.order,n=a.sort.type,l=0;l<c.length;l++)b=c[l],f+=b[a.data.attributes.HTML];a.box.html(f);a.options.cookies&&a.cookies.set_cookies();
g.isFunction(a.options.redraw_callback)&&a.options.redraw_callback(e,d,h,k,n)};a.update_view=function(){a.view_data=a.filter.filter_data(a.data);a.view_data=a.sort.sort_data(a.view_data);a.view_data=a.paging.set_paging(a.view_data);a.print(a.view_data)};var h=function(){a.filter.input_fields.keyup(function(){a.paging.cpage=0;a.update_view()});a.drop_down.update_paging_on_click(function(c){a.update_paging(c)});a.drop_down.update_sort_on_click(function(c,f,b){a.update_sorting(c,f,b)})},d=function(c,
f){a.options=g.extend({items_box:"",item_path:"",redraw_callback:"",cookies:!0,css_prefix:"jplist",pagingbox:".buttons",pageinfo:".info",paging_length:7,show_one_page:!0,items_on_page:5,filter:{},filter_path:"",sort:{},sort_order:"asc",sort_type:"text",sort_name:"",sort_dd_path:".sort-drop-down",paging_dd_path:".page-by"},c);a.container=f;a.box=a.container.find(a.options.items_box);a.items=a.container.find(a.options.item_path);a.helper=new g.fn.jplist.helper;a.data=new g.fn.jplist.data(a.options,
a.helper,a.container,a.items);a.sort=new g.fn.jplist.sort(a.options,a.helper,a.data);a.paging=new g.fn.jplist.paging(a.options,a.helper,a.container,a.items,function(b){a.print(b)});a.filter=new g.fn.jplist.filter(a.options,a.helper,a.container);a.drop_down=new g.fn.jplist.dropdown(a.options,a.helper,a.container,a.paging,a.sort);a.cookies=new g.fn.jplist.cookies(a.options,a.helper,a.data,a.filter,a.sort,a.paging,a.drop_down);a.container.addClass(a.options.css_prefix);h();a.options.cookies&&(a.cookies.get_cookies(),
a.drop_down.restore_dd());a.update_view()};g.fn.jplist=function(c){d(c,g(this));return a}})(jQuery);(function(g){var a={};a.set_cookies=function(){var h=a.paging.items_on_page,d=a.paging.cpage,c=a.sort.order,f=a.sort.type;a.set_cookie("s",a.sort.sort_name);a.set_cookie("iop",h);a.set_cookie("c",d);a.set_cookie("o",c);a.set_cookie("sn",f);a.set_cookie("id",a.data.url)};a.get_cookies=function(){var h=a.get_cookie("s"),d=a.get_cookie("iop"),c=a.get_cookie("c"),f=a.get_cookie("o"),b=a.get_cookie("sn");if(a.get_cookie("id")!=a.data.url)a.paging.cpage=0;else if(void 0!=c&&""!=c)a.paging.cpage=c;if(void 0!=
d&&""!=d)a.paging.items_on_page=d;if(a.sort.sort_name_exists(h)){if(void 0!=h&&""!=h)a.sort.sort_name=h;if(void 0!=f&&""!=f)a.sort.order=f;if(void 0!=b&&""!=b)a.sort.type=b}};a.set_cookie=function(a,d){var c=escape(d),f=new Date;f.setDate(f.getDate()+1);document.cookie=a+"="+c+";path=/; expires="+f.toUTCString()};a.get_cookie=function(a){var d,c,f,b;b=document.cookie.split(";");for(d=0;d<b.length;d++)if(c=b[d].substr(0,b[d].indexOf("=")),f=b[d].substr(b[d].indexOf("=")+1),c=c.replace(/^\s+|\s+$/g,
""),c==a)return unescape(f)};g.fn.jplist.cookies=function(h,d,c,f,b,e,g){a.options=h;a.helper=d;a.data=c;a.filter=f;a.sort=b;a.paging=e;a.drop_down=g;return a}})(jQuery);(function(g){var a={data:[],attributes:{ID:0,HTML:1,SORT_ARR:2,FILTER:3},url:document.URL,sort_indexes:[],filter_indexes:[]};g.fn.jplist.data=function(h,d,c,f){a.options=h;a.helper=d;a.box=c;a.items=f;var h=0,b;for(b in a.options.sort)a.sort_indexes["sort-"+b]=h,h++;b=0;for(var e in a.options.filter)a.filter_indexes["filter-"+e]=b,b++;for(c=0;c<a.items.length;c++){e=a.items.eq(c);b=a.helper.get_outer_html(e);var h=[],d=[],g;for(g in a.options.sort)h.push([e.find(a.options.sort[g]).text()]);for(var j in a.options.filter)d.push([e.find(a.options.filter[j]).text()]);
a.data.push([c,b,h,d])}return a}})(jQuery);(function(g){var a={dd_ul_list:"",dd_panel_list:"",sort_dd_panel:"",paging_dd_panel:""},h=function(){g(document).click(function(){a.dd_ul_list.hide()})},d=function(){a.dd_panel_list.bind("click",function(b){var e,f=0;b.stopPropagation();e=g(this).parent().find("ul");e.is(":visible")?a.dd_ul_list.hide(0):a.dd_ul_list.hide(0,function(){f++;f>=a.dd_ul_list.length&&e.show()})})},c=function(){for(var b,e=0;e<a.sort_dd.length;e++)b=a.sort_dd.eq(e),b=b.find("ul li"),b.click(function(){a.sort_dd.find(".panel").html(g(this).text())});
for(e=0;e<a.paging_dd.length;e++)b=a.paging_dd.eq(e),b=b.find("ul li"),b.click(function(){a.paging_dd.find(".panel").html(g(this).text())})},f=function(a){var e;e=a.find("li span:eq(0)").text();a.prepend("<div class='panel'>"+e+"</div>")};a.restore_dd=function(){var b,e,f,c;c=a.paging.items_on_page;for(var d=a.sort.sort_name,h=a.sort.order,g=a.sort.type,i=0;i<a.paging_dd.length;i++)e=a.paging_dd.eq(i),b=e.find("span[data-number='"+c+"']"),f=e.find(".panel"),0>=b.length&&(b=e.find("span[data-number='all']")),
f.html(b.text());for(i=0;i<a.sort_dd.length;i++){e=a.sort_dd.eq(i);c=e.find("ul li span");f=e.find(".panel");for(var m=0;m<c.length;m++)b=c.eq(m),(e=b.attr("data-sort")==d&&b.attr("data-order")==h&&b.attr("data-type")==g)&&f.html(b.text())}};a.update_paging_on_click=function(b){a.paging_dd.find("li").click(function(){var a=g(this).find("span").attr("data-number");g.isFunction(b)&&b(a)})};a.update_sort_on_click=function(b){a.sort_dd.find("li").click(function(){var a=g(this).find("span").attr("data-sort"),
f=g(this).find("span").attr("data-order"),c=g(this).find("span").attr("data-type");g.isFunction(b)&&b(a,f,c)})};a.if_paging_all=function(b){var e=!0;a.paging_dd.find("li span").each(function(){g(this).attr("data-number")==b&&(e=!1)});return e};g.fn.jplist.dropdown=function(b,e,g,j,k){a.options=b;a.helper=e;a.box=g;a.paging=j;a.sort=k;a.dd_list=a.box.find(".drop-down");a.sort_dd=a.box.find(a.options.sort_dd_path);a.paging_dd=a.box.find(a.options.paging_dd_path);for(e=0;e<a.sort_dd.length;e++)b=a.sort_dd.eq(e),
f(b);for(e=0;e<a.paging_dd.length;e++)b=a.paging_dd.eq(e),f(b);a.dd_ul_list=a.dd_list.find("ul");a.dd_panel_list=a.dd_list.find(".panel");a.sort_dd_panel=a.sort_dd.find(".panel");a.paging_dd_panel=a.paging_dd.find(".panel");d();h();c();return a}})(jQuery);(function(g){var a={support_placeholder:"placeholder"in document.createElement("input")},h=function(a){a=new String(a);a=a.replace(/[^a-zA-Z0-9]+/g,"");return a.toLowerCase()},d=function(a){for(var b=!0,e=0;e<a.length;e++)b&=a[e];return b},c=function(c){var b,e,d;if(!a.support_placeholder)for(var h=0;h<c.length;h++)b=c.eq(h),d=b.attr("placeholder"),b.wrap("<div class='placeholder-parent'></div>"),b=b.parent("div"),b.append("<div class='placeholder'></div>"),e=b.children(".placeholder"),e.text(d),
b.click(function(){g(this).find(".placeholder").hide()})};a.filter_data=function(c){for(var b=[],e,o,j,k=c.data,n,l,i,m,p=0;p<k.length;p++)o=k[p],e=o[c.attributes.FILTER],j=[],a.input_fields.each(function(){n=h(g(this).val());l=g(this).attr("data-name");i=c.filter_indexes["filter-"+l];m=e[i];-1!=h(m[0]).indexOf(n)||""==g.trim(n)?j.push(!0):j.push(!1)}),d(j)&&b.push(o);return b};g.fn.jplist.filter=function(d,b,e){a.options=d;a.helper=b;a.box=e;a.filter_pathes=e.find(d.filter_path);a.input_fields=a.filter_pathes.find("input");
c(a.input_fields);return a}})(jQuery);(function(g){var a={get_outer_html:function(a){for(var d="",c=a[0].attributes,f=a.html(),a=a[0].tagName.toString().toLowerCase(),d=d+("<"+a+" "),b=0;b<c.length;b++)null!=c[b].nodeValue&&""!=c[b].nodeValue&&(d+=c[b].nodeName+"=",d+="'"+c[b].nodeValue+"' ");return d+">"+f+("</"+a+">")}};g.fn.jplist.helper=function(){return a}})(jQuery);(function(g){var a={cpage:0,pagingView:[],pagingprev:"",pagingmid:"",pagingnext:"",first:"",prev:"",next:"",last:""},h=function(b){return Math.ceil(a.all_items_num/b)},d=function(){return a.cpage>=h(a.items_on_page)-1?h(a.items_on_page)-1:eval(a.cpage)+1},c=function(){var b,c,d="";if(0<=a.cpage&&a.cpage<h(a.items_on_page)){c=Math.floor(a.cpage/a.options.paging_length);b=a.options.paging_length*c;c=a.options.paging_length*(c+1);c>h(a.items_on_page)&&(c=h(a.items_on_page));for(var d=d+"<div class='pagesbox'>",
f=b;f<c;f++)d+="<span",f==a.cpage&&(d+=" class='current'"),b=f+1,d+=">"+b+"</span> ";a.pagingmid.html(d+"</div>")}},f=function(b,c,d){for(var f,g,h=eval(a.cpage)+1,i=0;i<a.pageinfo.length;i++)f=a.pageinfo.eq(i),g=f.attr("data-type"),"page"==g?f.html("Page "+h+" of "+eval(d)):f.html(eval(b)+1+" - "+eval(c)+" of "+eval(d))};a.set_paging=function(b){var d=a.cpage*a.items_on_page,j=d+eval(a.items_on_page),k=b.length;a.pagingView=b;if(j>b.length)j=b.length;a.all_items_num=k;b=b.slice(d,j);f(d,j,k);c();
0==a.cpage?a.pagingprev.addClass("hidden"):a.pagingprev.removeClass("hidden");a.cpage==h(a.items_on_page)-1?a.pagingnext.addClass("hidden"):a.pagingnext.removeClass("hidden");1==h(a.items_on_page)?a.options.show_one_page||a.pagingbox.addClass("hidden"):a.pagingbox.removeClass("hidden");g.isFunction(a.callback)&&a.callback(b);return b};var b=function(){a.first.click(function(){a.cpage=0;a.set_paging(a.pagingView)});a.prev.click(function(){a.cpage=0>=a.cpage?0:a.cpage-1;a.set_paging(a.pagingView)});
a.next.click(function(){a.cpage=d();a.set_paging(a.pagingView)});a.last.click(function(){a.cpage=h(a.items_on_page)-1;a.set_paging(a.pagingView)});a.pagingmid.find("span").on("click",function(){var b=g(this).text()-1;a.cpage=b;a.set_paging(a.pagingView)})};g.fn.jplist.paging=function(c,d,f,g,h){a.options=c;a.helper=d;a.box=f;a.items=g;a.callback=h;a.all_items_num=g.length;a.pageinfo=f.find(c.pageinfo);a.pagingbox=f.find(c.pagingbox);a.items_on_page=c.items_on_page;a.pagingbox.html("<div class='pagingprev'></div><div class='pagingmid'></div><div class='pagingnext'></div>");
a.pagingprev=a.pagingbox.find(".pagingprev");a.pagingmid=a.pagingbox.find(".pagingmid");a.pagingnext=a.pagingbox.find(".pagingnext");a.pagingprev.html("<span class='first'>&lt;&lt;</span><span class='prev'>&lt;</span>");a.pagingnext.html("<span class='next'>&gt;</span><span class='last'>&gt;&gt;</span>");a.first=a.pagingprev.find(".first");a.prev=a.pagingprev.find(".prev");a.next=a.pagingnext.find(".next");a.last=a.pagingnext.find(".last");b();return a}})(jQuery);(function(g){var a={},h=function(d,c){var f="";return f=d[a.data.attributes.SORT_ARR][a.data.sort_indexes["sort-"+c]]};a.sort_name_exists=function(d){var c=!1;if(void 0!=d&&""!=d)for(var f in a.options.sort)d==f&&(c=!0);return c};a.sort_data=function(d){switch(a.type){case "number":d.sort(function(c,d){var b=h(c,a.sort_name),e=h(d,a.sort_name),b=b.toString().replace(/[^0-9]+/g,""),e=e.toString().replace(/[^0-9]+/g,"");if("asc"==a.order){if(""==b)return 1;if(""==e)return-1}else{if(""==e)return 1;if(""==
b)return-1}return b-e});break;case "date":d.sort(function(c,d){var b=h(c,a.sort_name),e=h(d,a.sort_name),b=new Date(Date.parse(b)),e=new Date(Date.parse(e));return b>e?1:-1});break;default:d.sort(function(c,d){var b=h(c,a.sort_name),e=h(d,a.sort_name);return void 0==b||void 0==e?b>e?1:-1:b.toString().toLowerCase()>e.toString().toLowerCase()?1:-1})}"desc"==a.order&&d.reverse(function(c,d){var b=h(c,a.sort_name),e=h(d,a.sort_name);return void 0==b||void 0==e?b>e?1:-1:b.toString().toLowerCase()>e.toString().toLowerCase()?
1:-1});return d};g.fn.jplist.sort=function(d,c,f){a.options=d;a.helper=c;a.data=f;a.order=d.sort_order;a.sort_name=d.sort_name;a.type=d.sort_type;return a}})(jQuery);
